name: Release Workflow

on:
  push:
    tags:
      - '*'

jobs:
  run:
    name: Run action
    runs-on: ubuntu-latest

    steps:
    - name: --- Checkout repository
      uses: actions/checkout@v1
    
    - name: --- Setup SourcePawn Compiler
      uses: rumblefrog/setup-sp@master
      with:
        version: "1.10.x"
    
    - name: --- Verify compiler
      run: |
        which spcomp
        spcomp -i$includePath -iscripting/include scripting/FirePlayersStats.sp -O2 -v2 -oFirePlayersStats.smx
        
    - name: --- Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: true
        prerelease: false
